import { Button, VerticalBox } from "std-widgets.slint";
import { SheetHome } from "./SheetHome.slint";
import { Home } from "./Home.slint";
import { SheetInsert } from "./SheetInsert.slint";
import { SheetShow } from "./SheetShow.slint";
import { CurrentPage,Router } from "./global.slint";

component Routes {
    if Router.page == CurrentPage.Home : Home {
        height: 90%;
        width: 90%;
    }
    if Router.page == CurrentPage.SheetHome: SheetHome {}
    if Router.page == CurrentPage.SheetShow: SheetShow {}
    if Router.page == CurrentPage.SheetInsert: SheetInsert {}
}

export component AppWindow inherits Window {
    Routes {
        height: 100%;
        width: 100%;
    }
}
