import { Button, VerticalBox , Switch} from "std-widgets.slint";
import { Router,CurrentPage,Name } from "./global.slint";

component TopBar inherits HorizontalLayout {
        Button {
            width: 5%;
            text: "<-";
            clicked => {
                Router.page = CurrentPage.Home
            }
        }
        VerticalBox {
            Text {
                font-size: 16px;
                text: "search bar";
            }
            HorizontalLayout {
                Text {text: "begin date";}
                Text {text: "end date";}
            }
        }
        Button {
            width: 5%;
            text: "+";
            clicked => {
                Router.page = CurrentPage.SheetInsert
            }
        }
}

export component SheetHome inherits VerticalBox {
    out property <int> offset : 0;
    in property <[Name]> sheets_names: [
        {id : "1",name : "name1"},
        {id : "2",name : "name2"},
        {id : "3",name : "name3"},
        {id : "4",name : "name4"},
        {id : "5",name : "name5"},
    ];
    TopBar {
        height: 10%;
    }
    VerticalBox {
        alignment: center;
        Button {
            height: 5%;
            text: "↑";
            clicked => {
                if (offset != 0) {
                    offset = offset -1;
                }
            }
        }
        VerticalBox {
            height: 70%;
            for name in sheets-names : Button {
                height: 15%;
                text: name.name;
                clicked => {
                    Router.prepare-sheet-show(name.id);
                    Router.page = CurrentPage.SheetShow;
                }
            }
        }
        Button {
            height: 5%;
            text: "↓";
            clicked => {
                if (sheets-names.length == 5) {
                    offset = offset +1;
                }
            }
        }
    }
}
